version: '3'
name: ghfdb

volumes:
  postgres: {}
  postgres_backups: {}
  media: {}

services:

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django
    image: production_django
    depends_on:
      - postgres
      - redis
      - minio
    command: start-django
    env_file:
      - stack.env
  postgres:
    image: geoluminate/postgis:latest
    env_file:
      - stack.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_backups:/backups
  redis:
    image: redis:6
  celeryworker:
    <<: *django
    command: start-celeryworker
    labels: []
  celerybeat:
    <<: *django
    command: start-celerybeat
    labels: []
  flower:
    <<: *django
    command: start-flower
  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - media:/minio
    env_file:
      - stack.env
    command: server /minio
  traefik:
    image: "geoluminate/traefik"
    env_file:
      - stack.env
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

