# SEE: docs.fairdm/deployment
version: "3.7"
name: ghfdb

services:
  django:
    image: ghcr.io/ihfc-iugg/ghfdb-portal:latest
    environment:
      - DJANGO_SITE_NAME=Heatflow.world
      - DJANGO_SECURE_SSL_REDIRECT=False
      - DJANGO_SUPERUSER_EMAIL=super.user@example.com
    env_file:
      - stack.env
    ports:
      - 80:5000