version: '3'
name: ghfdb_local
volumes:
  ghfdb_local_postgres_data: {}
  ghfdb_local_postgres_data_backups: {}
  ghfdb_external_apps:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'C:\Users\jennings\Documents\geoluminate_apps'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/geoluminate/local
    image: ghfdb_local
    depends_on:
      - postgres
      - redis
      - mailhog
    working_dir: /app
    volumes:
      - ghfdb_external_apps:/external_apps
      - ./:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /external_apps/geoluminate/bin/local/django
    entrypoint: /external_apps/geoluminate/bin/entrypoint
     # entrypoint: "tail -f /dev/null"

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: ghfdb_production_postgres
    volumes:
      - ghfdb_local_postgres_data:/var/lib/postgresql/data
      - ghfdb_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    ports: []
    command: /external_apps/geoluminate/bin/local/celery_worker

  celerybeat:
    <<: *django
    ports: []
    command: /external_apps/geoluminate/bin/local/celery_beat

  flower:
    <<: *django
    ports:
      - "5555:5555"
    command: /external_apps/geoluminate/bin/local/celery_flower

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  docs:
    <<: *django
    working_dir: /app/docs
    ports:
      - "9000:9000"
    command: /external_apps/geoluminate/bin/local/docs