version: '3'
name: ghfdb_local

volumes:
  postgres: {}
  postgres_backups: {}
  media: {}

services:

  django: &django
    build:
      context: .
      dockerfile: ./compose/django/local
    image: ghfdb_local_django
    depends_on:
      - postgres
      - redis
      - minio
    volumes:
      - ./:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - 8000:8000
      - 5678:5678
    command: /app/bin/local/django
    entrypoint: /app/bin/entrypoint
    # entrypoint: "tail -f /dev/null"

  postgres:
    image: geoluminate/postgis:latest
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
  redis:
    image: redis:6
  # celeryworker:
  #   <<: *django
  #   ports: []
  #   command: /app/bin/local/celery_worker

  # celerybeat:
  #   <<: *django
  #   ports: []
  #   command: /app/bin/local/celery_beat

  # flower:
  #   <<: *django
  #   ports:
  #     - "5555:5555"
  #   command: /app/bin/local/celery_flower

  # docs:
  #   <<: *django
  #   working_dir: /app/docs
  #   ports:
  #     - "9000:9000"
  #   command: /app/bin/local/docs
  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - media:/minio
    env_file:
      - ./.envs/.local/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /minio
