version: '3'
name: ghfdb_production

volumes:
  postgres: {}
  postgres_backups: {}
  media: {}

services:

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django
    image: production_django
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - ./compose/production/.envs/.django
      - ./compose/production/.envs/.postgres
    command: start-django
    ports:
      - "5000:5000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.django.rule=Host(`localhost`)
      - traefik.http.routers.django.entrypoints=web
      - traefik.http.services.django.loadbalancer.server.port=5000
      - traefik.http.middlewares.csrf.headers.hostsProxyHeaders=X-CSRFToken
  postgres:
    image: geoluminate/postgis:latest
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_backups:/backups
    env_file:
      - ./compose/production/.envs/.postgres
  redis:
    image: redis:6
  celeryworker:
    <<: *django
    command: start-celeryworker
    ports: []
    labels: []
  celerybeat:
    <<: *django
    command: start-celerybeat
    ports: []
    labels: []
  flower:
    <<: *django
    command: start-flower
    ports:
      - "5555:5555"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.rule=Host(`flower.localhost`)"
      - "traefik.http.routers.flower.entrypoints=web"
      - traefik.http.services.flower.loadbalancer.server.port=5555
  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - media:/minio
    env_file:
      - ./compose/production/.envs/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /minio
    labels:
      - traefik.enable=true
      - traefik.http.routers.media.entrypoints=web
      - traefik.http.routers.media.rule=Host(`media.localhost`)
      - traefik.http.routers.media.service=media
      - traefik.http.services.media.loadbalancer.server.port=9000

      - traefik.http.routers.minio.entrypoints=web
      - traefik.http.routers.minio.rule=Host(`media.localhost`) && PathPrefix(`/dashboard`)
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9001
  traefik:
    image: "traefik:v2.11"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"
      - "8080:8080"
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
