version: '3'
name: ghfdb_production

volumes:
  postgres: {}
  postgres_backups: {}
  traefik: {}
  media: {}

services:

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django
    image: production_django
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - ./compose/production/.envs/.django
      - ./compose/production/.envs/.postgres
    command: start-django
  postgres:
    image: geoluminate/postgis:latest
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_backups:/backups
    env_file:
      - ./compose/production/.envs/.postgres
  redis:
    image: redis:6
  # celeryworker:
  #   <<: *django
  #   command: start-celeryworker
  # celerybeat:
  #   <<: *django
  #   command: start-celerybeat
  # flower:
  #   <<: *django
  #   command: start-flower
  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - media:/minio
    env_file:
      - ./compose/production/.envs/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /minio
  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik
    image: traefik
    depends_on:
      - django
    volumes:
      - traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"
      # - "0.0.0.0:8080:8080"

