# THESE ARE THE EXACT SAME SETTINGS AS PRODUCTION.YML, BUT WITHOUT THE REDIRECTION TO HTTPS
# THIS IS USEFUL TO TEST THE PRODUCTION SETUP LOCALLY

version: "3.7"
name: ghfdb_production

volumes:
  postgres: {}
  postgres_backups: {}
  media: {}

services:

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django
    image: production_django
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - stack.env
    command: start-django
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.django.rule=Host(`${DJANGO_DOMAIN_NAME:-localhost}`)
      - traefik.http.routers.django.entrypoints=http
      - traefik.http.services.django.loadbalancer.server.port=5000
      - traefik.http.middlewares.csrf.headers.hostsProxyHeaders=X-CSRFToken
  postgres:
    image: geoluminate/postgis
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_backups:/backups
    restart: always
    env_file:
      - stack.env
  redis:
    image: redis:6
    restart: always
  celeryworker:
    <<: *django
    command: start-celeryworker
    labels: []
  celerybeat:
    <<: *django
    command: start-celerybeat
    labels: []
  flower:
    <<: *django
    command: start-flower
    labels:
      - traefik.enable=true
      - traefik.http.routers.tasks.rule=Host(`tasks.${DJANGO_DOMAIN_NAME:-localhost}`)
      - traefik.http.routers.tasks.entrypoints=http
      - traefik.http.routers.tasks.service=tasks
      - traefik.http.services.tasks.loadbalancer.server.port=5555
  minio:
    image: quay.io/minio/minio
    volumes:
      - media:/minio
    env_file:
      - stack.env
    command: server /minio
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.media.service=media
      - traefik.http.routers.media.entrypoints=http
      - traefik.http.routers.media.rule=Host(`media.${DJANGO_DOMAIN_NAME:-localhost}`)
      - traefik.http.services.media.loadbalancer.server.port=9000

      - traefik.http.routers.minio.service=minio
      - traefik.http.routers.minio.entrypoints=http
      - traefik.http.routers.minio.rule=Host(`minio.${DJANGO_DOMAIN_NAME:-localhost}`)
      - traefik.http.services.minio.loadbalancer.server.port=9001
  traefik:
    image: "traefik:v2.11"
    restart: always
    volumes:
      - ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    command:
      # - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --api=true

      - --entrypoints.http.address=:80
      # - --entrypoints.http.http.redirections.entryPoint.to=https # COMMENTED OUT TO DISABLE REDIRECTION TO HTTPS
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls.certresolver=${TRAEFIK_CERT_RESOLVER}

      # LetsEncrypt Staging Server - uncomment when testing
      # - --certificatesResolvers.letsencrypt.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=http
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_CERT_EMAIL:-admin@localhost}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json

    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${DJANGO_DOMAIN_NAME:-localhost}`)
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
