[tool.poetry]
name = "global-heat-flow-database"
version = "0.1.0"
description = "Web application for the IHFC Global Heat Flow Database"
authors = ["Sam <samuel.scott.jennings@gmail.com>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
django-literature = {git = "https://github.com/SSJenny90/django-literature"}
django-laboratory = {git = "https://github.com/SSJenny90/django-laboratory"}
django-ror = {git = "https://github.com/SSJenny90/django-ror"}
geoluminate-earth-science = {git = "https://github.com/Geoluminate/geoluminate-earth-science"}
django-controlled-vocabulary = {git = "https://github.com/SSJenny90/django-controlled-vocabulary"}
geoluminate = {path = "../geoluminate", develop = true}


[tool.poetry.group.dev.dependencies]
coverage = "^7.2.1"
autopep8 = "^2.0.2"
black = "^23.1.0"
pytest = "^7.2.2"
factory-boy = "^3.2.1"
django-debug-toolbar = "^3.8.1"
django-extensions = "^3.2.1"
django-coverage-plugin = "^3.0.0"
pytest-django = "^4.5.2"
django-stubs = "^1.15.0"
pytest-sugar = "^0.9.6"
djangorestframework-stubs = "^1.9.1"
flake8 = "^6.0.0"
flake8-isort = "^6.0.0"
pylint-django = "^2.5.3"
pylint-celery = "^0.3"
pre-commit = "^3.1.1"
django-debug-toolbar-template-profiler = "^2.1.0"
werkzeug = {extras = ["watchdog"], version = "^2.2.3"}
ipdb = "^0.13.11"
psycopg2 = "^2.9.5"
watchfiles = "^0.18.1"
invoke = "^2.0.0"



[tool.poetry.group.docs.dependencies]
sphinx = "^6.1.3"
sphinx-copybutton = "^0.5.1"
sphinxext-opengraph = "^0.8.1"
sphinx-book-theme = "^1.0.0"
myst-parser = "^0.19.1"
sphinx-autobuild = "^2021.3.14"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
