version: '3'
name: ghfdb_staging

volumes:
  postgres: {}
  postgres_backups: {}
  media: {}

networks:
  traefik:
    external: true

services:

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django
    image: production_django
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - ./compose/production/.envs/.django
      - ./compose/production/.envs/.postgres
    command: start-django
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.django.tls=true
      - traefik.http.routers.django.rule=Host(`env.rz-vm71.gfz-potsdam.de`)
      - traefik.http.routers.django.entrypoints=https
      - traefik.http.services.django.loadbalancer.server.port=5000
      - traefik.http.middlewares.csrf.headers.hostsProxyHeaders=X-CSRFToken
  postgres:
    image: geoluminate/postgis:latest
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_backups:/backups
    env_file:
      - ./compose/production/.envs/.postgres
  redis:
    image: redis:6
  celeryworker:
    <<: *django
    command: start-celeryworker
    labels:
      - "traefik.enable=false"
  celerybeat:
    <<: *django
    command: start-celerybeat
    labels:
      - "traefik.enable=false"
  flower:
    <<: *django
    command: start-flower
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.rule=Host(`flower.env.rz-vm71.gfz-potsdam.de`)"
      - "traefik.http.routers.flower.entrypoints=https"
      - traefik.http.services.flower.loadbalancer.server.port=5555
  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - media:/minio
    env_file:
      - ./compose/production/.envs/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /minio
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.media.entrypoints=https
      - traefik.http.routers.media.rule=Host(`env.rz-vm71.gfz-potsdam.de`) && PathPrefix(`/media`)
      - traefik.http.routers.media.service=media
      - traefik.http.services.media.loadbalancer.server.port=9000

      - traefik.http.routers.minio.entrypoints=https
      - traefik.http.routers.minio.rule=Host(`env.rz-vm71.gfz-potsdam.de`) && PathPrefix(`/media`) && PathPrefix(`/dashboard`)
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9001




