version: '3'
name: ghfdb_staging

volumes:
  postgres: {}
  postgres_backups: {}
  media: {}

networks:
  traefik:
    external: true

services:

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django
    image: production_django
    depends_on:
      - postgres
      - redis
      - minio
    command: start-django
    ports:
      - "5000:5000"
    env_file:
      - stack.env
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.django.tls=true
      - traefik.http.routers.django.rule=Host(`${DJANGO_HOST_NAME}`)
      - traefik.http.routers.django.entrypoints=https
      - traefik.http.services.django.loadbalancer.server.port=5000
      - traefik.http.middlewares.csrf.headers.hostsProxyHeaders=X-CSRFToken
  postgres:
    image: geoluminate/postgis:latest
    env_file:
      - stack.env
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_backups:/backups
  redis:
    image: redis:6
  celeryworker:
    <<: *django
    command: start-celeryworker
    ports: []
    labels: []
  celerybeat:
    <<: *django
    command: start-celerybeat
    ports: []
    labels: []
  flower:
    <<: *django
    command: start-flower
    ports:
      - "5555:5555"
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.flower.tls=true
      - "traefik.http.routers.flower.rule=Host(`tasks.${DJANGO_HOST_NAME}`)"
      - "traefik.http.routers.flower.entrypoints=https"
      - traefik.http.services.flower.loadbalancer.server.port=5555
  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - media:/minio
    env_file:
      - stack.env
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /minio
    networks:
      - default
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.media.tls=true
      - traefik.http.routers.media.entrypoints=https
      - traefik.http.routers.media.rule=Host(`media.${DJANGO_HOST_NAME}`)
      - traefik.http.routers.media.service=media
      - traefik.http.services.media.loadbalancer.server.port=9000

      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.entrypoints=https
      - traefik.http.routers.minio.rule=Host(`media.${DJANGO_HOST_NAME}`) && PathPrefix(`/dashboard`)
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9001




