version: '3'
name: ghfdb_staging

volumes:
  postgres: {}
  postgres_backups: {}
  media: {}

services:

  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django
    image: production_django
    depends_on:
      - postgres
      - redis
      - minio
    env_file:
      - ./compose/production/.envs/.django
      - ./compose/production/.envs/.postgres
    command: start-django
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`env.rz-vm71.gfz-potsdam.de`)"
      - "traefik.http.routers.django.entrypoints=https"
      - traefik.http.services.myminio.loadbalancer.server.port=5000
      - "traefik.http.middlewares.csrf.headers.hostsProxyHeaders=X-CSRFToken"
  postgres:
    image: geoluminate/postgis:latest
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres_backups:/backups
    env_file:
      - ./compose/production/.envs/.postgres
  redis:
    image: redis:6
  celeryworker:
    <<: *django
    command: start-celeryworker
    labels:
      - "traefik.enable=false"
  celerybeat:
    <<: *django
    command: start-celerybeat
    labels:
      - "traefik.enable=false"
  flower:
    <<: *django
    command: start-flower
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flower.rule=Host(`flower.env.rz-vm71.gfz-potsdam.de`)"
      - "traefik.http.routers.flower.entrypoints=https"
      - traefik.http.services.myminio.loadbalancer.server.port=5555
  minio:
    image: quay.io/minio/minio:latest
    volumes:
      - media:/minio
    env_file:
      - ./compose/production/.envs/.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /minio
    labels:
      - traefik.enable=true
      - traefik.http.routers.myminio.entrypoints=https
      - traefik.http.routers.myminio.rule=Host(`media.env.rz-vm71.gfz-potsdam.de`)
      - traefik.http.routers.myminio.service=media
      - traefik.http.services.myminio.loadbalancer.server.port=9000

      - traefik.http.routers.myminioadmin.entrypoints=https
      - traefik.http.routers.myminioadmin.rule=Host(`media.env.rz-vm71.gfz-potsdam.de`) && PathPrefix(`/dashboard`)
      - traefik.http.routers.myminioadmin.service=mediaadmin
      - traefik.http.services.myminioadmin.loadbalancer.server.port=9001
