name: Publish container to GitHub Container Registry

on:
  release:
    types: [released]
  # push:
    # branches: ["main"]
  push:
    tags:
      - v20**
  # Allows you to manually run the workflow
  # workflow_dispatch:

jobs:

  docker:
    name: Publish to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically generates this for the actor


      # - name: Log in to GitHub Container Registry
      #   run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/ihfc-iugg/ghfdb-portal
          tags: |
            ${{ github.ref_name }}
            latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "📦 Build and push image to GHCR"
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: deploy/production  # Path to the Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Log out from GitHub Container Registry
        run: docker logout
